EMCECS/clarity-react

src/forms/input/Input.tsx

Adding facility to use className in Input when isboxed is true.
We are using className "form-control modded" from Dell component to display  +/- button in Input.
We can use following code to display numeric +/- button in Input form control. 
<form className="boxed token-boxed">
<div className="form-block">
<Input
className="form-control modded"
name="test"
isBoxed={true}
placeholder="" type="number"
/>
</div>
</form>

[FLEX-522] : Adding numeric +/- button in Input Form Control.

---

src/datagrid/DataGrid.tsx

For pagination the totalItems are total items present in back-end and not just length of data-gird rows.
So changed logic in updateRows() accordingly.

Made totalItems parameter of updateRows() optional  for pagination

---

src/datagrid/DataGrid.tsx

when we use filtering along with pagination and if user is on page other than first page then first item index in footer label is incorrect.
**Before Fix:**
**After Fix:**

Fixed issue of firstitem in pagination label is incorrect

---

src/wizards/Wizard.stories.tsx
src/wizards/Wizard.tsx

This PR has taken care of following things.
-     Allow wizard to close at any/each step. Also add story for the same
-     Make css of wizard button configurable
-     Hide previous button

Changes in wizard to enable hide of previous and cancel button

---

package.json
src/datagrid/DataGrid.tsx
src/datagrid/DataGridFilter.tsx
src/datagrid/DataGridValues.tsx
src/wizards/Wizard.stories.tsx
src/wizards/Wizard.tsx

This PR has fixed following bugs:
- FLEX-2260 :  Common Component -> Data Grid -> Footer bar does not update even if the Data Grid is updated (https://asdjira.isus.emc.com:8443/browse/FLEX-2260)
- FLEX-2190 : Object Store/Common Components - Events - Sorting ICONS not working as expected (https://asdjira.isus.emc.com:8443/browse/FLEX-2190)
-  FLEX-2188 Object Store - Buckets - Showing worng number in footer (https://asdjira.isus.emc.com:8443/browse/FLEX-2188)
- FLEX-2040 : Do not show multiple sorting arrows at a time in datagrid (https://asdjira.isus.emc.com:8443/browse/FLEX-2040)
- Removed multiple setState() from DataGridFilter component
- Added prop to hide/show step title in wizard
**Datagrid:**
- With filter box and only one sorting arrow
- Updating datagrid footer …

Fix for multiple wizard and datagrid issues

---

src/forms/input/Input.tsx

Restrict keydown for 'e' only if input type is number. Other non numeric keys are disabled by default as we set type=="number".  
Note: type="number" feature supported by following browsers
https://www.w3schools.com/tags/att_input_type_number.asp
Tested for chrome and firefox (Both latest versions)
-> for Chrome it worked
-> for Firefox it didn't work.

[FLEX-2214] Bugfix: multiple e bug in number input

---

src/wizards/CustomStepComponent.tsx
src/wizards/Wizard.stories.tsx
src/wizards/Wizard.tsx

To fix Flex 2216 and 2218 we need to replace functional call backs to wizard steps with promises so that wizard will wait till completion of onStepSubmit/onNext/onPrevious function before going to next/previous step
**Bugs:**
- https://asdjira.isus.emc.com:8443/browse/FLEX-2218
- https://asdjira.isus.emc.com:8443/browse/FLEX-2216

Added promises for wizard callbacks rather than normal function call

---

package.json
src/datagrid/DataGrid.tsx

Fixed issue of pagination footer is not changing to normal footer for rows less than page size.

Replace pagination footer with normal footer if rows are less than page size

---

src/datagrid/DataGrid.tsx

Due to PR https://github.com/EMCECS/clarity-react/pull/102 basic datagrid footer was  not rendering correctly. In this PR I have fixed it.
**Screen-shots:**
Without pagination Footer:
With pagination Footer:
With pagination Footer and Filtering:

Fixed issue of basic footer in datagrid

---

package.json
src/wizards/Wizard.tsx

We are using **navigationClick()** function in plugin code (https://eos2git.cec.lab.emc.com/ECS/ecs-flex-vsphere-plugin) for  **newObjectStore->Review page -> Edit**. So that on click of 'Edit' user can go back to respective step. There we can not pass whole 'Step' object so reverting back parameter for this function from Step object to stepId.
**Bug**: https://jira.cec.lab.emc.com:8443/browse/OBSDEF-109
Working of Edit on review page of new object store wizard :
Working of custom step navigation click :

Fixed navigation click not working issue in wizard

---

package.json
src/datagrid/DataGridFilter.tsx

Due to same 'name' attribute 'DataGridFilter' was keeping history of all filters.
**Bug:**
- https://jira.cec.lab.emc.com:8443/browse/OBSDEF-6
Before Fix:
After Fix:

fixed issue of datagrid filter keeps generic history

---

package.json
src/datagrid/ClassNames.tsx
src/datagrid/DataGrid.tsx
src/datagrid/DataGridFilter.tsx
src/datagrid/DataGridValues.tsx

**Description :**
This PR has taken care of following things.
-  Added loading spinner in datagrid on pagination, filtering, and sorting
-  Fixed issue of  missing bottom border of last row in datagrid
**Bugs :**
- https://jira.cec.lab.emc.com:8443/browse/OBSDEF-24
**Screen Shots :**
Added border for last row 
Added spinners for pagination , filtering and sorting

Added loading spinner in datagrid

---

package.json
src/forms/button/ButtonGroup.tsx
src/forms/radio/RadioButtonGroup.tsx

**Description:** 
- Fixed issue of ButtonGroup and RadioButtonGroup components not getting updated after changes in props.
Before Template Selection:
After Template Selection:
Normal rendering of button group and radio button group:

Fix issue of button group not getting updated after changes in props

---

package.json
src/forms/toggle/Toggle.tsx

Fixed issue of toggle button not getting updated on prop change
Before Template selection:
After Template selection:
Normal Toggle:

Fixed issue of toggle button not geting update

---

src/datagrid/ClassNames.tsx
src/datagrid/DataGrid.stories.tsx
src/datagrid/DataGrid.tsx
src/datagrid/DataGridValues.tsx

- Added provision in datagrid to show number of selected rows in datagrid footer
- Added story for same in storybook
- Changed CSS for select cells as per vMware clarity version 3
For 3 selected rows : 
Deselect 1 row :

Added feature in datagrid to show selected row count

---

package.json
src/datagrid/ClassNames.tsx
src/datagrid/DataGrid.tsx
src/datagrid/DataGridColumnResize.tsx

- Added feature in datagrid to change width of datagrid column using width dragger
**Bug:**
- https://jira.cec.lab.emc.com/browse/OBSDEF-1308
Original Grid
After increasing column width:
After decreasing column width:
Min width indicator:

[OBSDEF-1308] datagrid column width

---

package.json
src/newWizard/Wizard.stories.tsx
src/newWizard/Wizard.tsx

**Description :**
- Added code in wizard to configure visibility of wizard footer buttons
- Added story for same in storybook
**Screen shot:**
wizard with single 'Apply' button and no 'Next' and 'Back' buttons. This wizard will close on Apply and Cancel click

Wizard  : Added provision to configure  footer buttons

---

package.json
src/modals/Modal.stories.tsx
src/modals/Modal.tsx

JIRA: https://jira.cec.lab.emc.com/browse/OBSDEF-3016
Feature:  Model component was supporting fix sizes for the modal sizing.  Due to this the wrong sizes were getting applied to the Modal Dialogs in case of Standalone application.  So we have added Custom size, where the width and height are directly applied to the Modal. 
**Screenshots:**
with custom style
With Custom Classname

[obsdef-3016] -  Added custom size for modals and added storybook

---

package.json
src/datagrid/DataGrid.stories.tsx
src/datagrid/DataGrid.tsx
src/newWizard/Wizard.stories.tsx
src/newWizard/Wizard.tsx
src/newWizard/WizardFooter.tsx
src/newWizard/WizardNavigation.tsx
src/newWizard/WizardStep.tsx

- Added `isApplying `prop in wizard to show loading spinner on click of Apply
- Added story in storybook for same
- Change signature of select callbacks in datagrid. This change will not harm any existing implementation using datagrid. 
**JIRA:**
- https://jira.cec.lab.emc.com/browse/OBSDEF-3306 
**Testing:**
- Verified working on this changes with vsphere plugin code as well.
Storybook:

[OBDEF-3306] Wizard - add loading spinner on click of Apply

---

package.json
src/datagrid/DataGrid.tsx
src/forms/select/Select.stories.tsx
src/forms/select/Select.tsx
src/newWizard/Wizard.stories.tsx
src/newWizard/Wizard.tsx
src/newWizard/WizardFooter.tsx
src/newWizard/WizardStep.tsx

**Description :** 
- Added loading spinner in wizard step
- Fixed below console errors on datagrid and select component
console errors: 
`Warning: Can't call setState on a component that is not yet mounted. This is a no-op, but it might indicate a bug in your application. Instead, assign to `this.state` directly or define a `state = {};` class property with the desired state in the DataGrid component.
in DataGrid (at DataGrid.stories.tsx:88)
in div (at DataGrid.stories.tsx:87)
in div (created by Story)`
`react-dom.development.js:88 Warning: Use the `defaultValue` or `value` props on <select> instead of setting `selected` on <option>.
in option (at DataGrid.tsx:1147)
in select (at DataGrid.tsx:1140)`
**JIRA:**
- https://jira.cec.lab.emc.com/browse/OBSDEF-3306
- …

[OBSDEF-3306] [OBSDEF-3410] Added loading spinner in wizard step and fix console errors

---

package.json
src/forms/input/Input.stories.tsx
src/forms/input/Input.tsx
src/forms/password/Password.stories.tsx
src/forms/password/Password.tsx

Description:
Added onKeyPress in Password to support only numeric values in PIN in SupportAssist.
Added title for Input.
Added story.
Testing:
http://10.249.253.4:6006
Screenshots:

Added onKeyPress in Password for numeric password

---

package.json
src/datagrid/DataGrid.tsx

- Fixed issue on datagrid loading spinner when `props.isLoading `is `false
- Fixed CSS issue on scrolling of selectAll and empty datagrid header
**JIRA:** 
- https://jira.cec.lab.emc.com/browse/OBSDEF-4118
**Testing:**

[OBSDEF-4118] Fixed issue of datagrid loading spinner and scrolling of selectAll column header

---

src/datagrid/DataGrid.stories.tsx
src/datagrid/DataGridStoriesData.tsx
src/datagrid/DataGridValues.tsx
src/forms/password/Password.stories.tsx
src/forms/password/Password.tsx

Refer - https://jira.cec.lab.emc.com/browse/OBSDEF-4343
Adding Read-only password to datagrid row
As per required Acceptance Criteria
1. Password has been aligned in datagrid row.
2. Password is made readonly 
Refer image for - **Read only password in Datagrid**
Refer GIF for - **Read-only password**

[OBSDEF-4343] IAM UI: Adding password read-only in Datagrid row

---

package.json
yarn.lock

Updated and tested `clr/ui` and` clr/icons `packages to version 4.0.x
**JIRA:**
- https://jira.cec.lab.emc.com/browse/OBSDEF-4220

[OBSDEF-4220] Updated versions for clr-icons and clr-ui to 4.0.8

---

package.json
src/forms/common/DebounceUtils.ts
src/forms/datalist/DataList.stories.tsx
src/forms/datalist/DataList.tsx
src/forms/input/Input.stories.tsx
src/forms/input/Input.tsx

In 0.25.4 build, the debounce was made mandatory for all text fields. This had sideeffect on the Input with Type="number".  So in this PR, we have introduced one more Prop for **DataList** and **Input** components.
- debounce   ->  optional field, boolean. This need to be set to false if you dont want debounce on the input field
- debounceTime -> optional field, number. Default debounce Time is 500ms, if you want to change that time, then you can set these numbers. 
**Debounce Set False**
**Debounce Set True - with 1 Second debounceTime **

Feature [OBSDEF-5812] - debounce behaviour enhacements

---

package.json
src/datagrid/DataGridFilter.tsx

https://jira.cec.lab.emc.com/browse/OBSDEF-4746
1) Added Debounce of 500ms
Filters on ObjectStoreList, events, issues pages fires too many backend calls, as every keystroke fires one backend call. This is not really performant, so to reduce this behaviour we have added debounce with 500ms to all the text based filters.
2) DataGridFilter didnt had option to clear themself, so exposed a method to clear the dataGrid Filter by passing Empty string
3) Introducted **disabled** prop to allow disabling filter textbox if the props is applied. This is important to avoid user typing into the textbox when some backend calls are already in progress and loader is visible.  In current implementation, the DataGrid Loader does not block user from keep typing into filter.  So this disabled prop would help …

Added debounce feature to Filters and also added fix for clearing filter

---

src/newWizard/Wizard.stories.tsx
src/newWizard/Wizard.tsx
src/newWizard/WizardFooter.tsx

Description:
Added props for disabling previous button as the previous button is being used as Quick-create button in New Object Store.
Screenshots:

[OBSDEF-7469] Added prop for disabling previous button

---

package.json
src/datagrid/DataGridStoriesData.tsx
src/datagrid/HideShowColumns.tsx

This PR includes fix for:
Hide and show column component should render label as display name when available
JIRA-
https://jira.cec.lab.emc.com/browse/OBSDEF-9382

[OBSDEF-9382] Hide and show column component should render label as display name when available

---

src/datagrid/DataGrid.stories.tsx
src/datagrid/DataGrid.tsx

Changes in this PR:
-> Placeholder text is now "No items found!" instead of "We couldn't find any items!"
-> Centered icon in empty container
-> Updated story to reflect the same.

[OBSDEF - 10007] Changed placeholder text and centered the message to center of datagrid

---

package.json
src/datagrid/DataGrid.tsx

This PR includes fix for:
Removing sorting when detail pane is open
Refer GIF

[OBSDEF-9781] On expand when account alias/object store name sorting is applied it redirects to the list page

---

package.json
src/datagrid/DataGrid.tsx

[OBSDEF-11298]: Adding "hideSelectAll" prop in Datagrid to make "Select all" checkbox optional
Defect: https://jira.cec.lab.emc.com/browse/OBSDEF-11298
Test screenshots -
Default - its False
When "hideSelectAll" set as true -

[OBSDEF-11298]: Adding "hideSelectAll" prop in Datagrid to make "Select all" checkbox optional

---

.github/workflows/github-actions-push-master.yml

Remove action to trigger job automatically on master push. this job can be run manually.

Stop-Job-to-run-on-master-push

---

package.json
src/layout/nav/Header.stories.tsx
yarn.lock

Upgraded clr/ui and clr/icons package to latest version 12.0.8
Not major breaking changes observed, fixed OBSDEF-4339 icons overlapping issue.

Upgrade clr/ui and clr/icons package to latest version 12.0.8 and fixes

---

package.json
src/forms/tooltip/ToolTip.tsx

Added optional parameter for solid icon in tooltip required for DDS Wrapper (isSolidIcon)
type ToolTipProps = {
direction?: ToolTipDirection;
size?: ToolTipSize;
status?: ToolTipStatus;
style?: any;
iconSize?: number;
shape?: string;
className?: string;
dataqa?: string;
isSolidIcon?: boolean;
};

Feature-obsdef-13999 Added optional parameter for solid icon in tooltip

---

package.json
src/layout/vertical-nav/VerticalNavGroup.tsx

The `caret ` icon direction should be downward for expansion and right for the collapse. But for the vertical nav group, it was showing it incorrectly.

[OBSDEF-16020] Correct direction of expand and collapse vertical nav group

---

package.json
src/datagrid/DataGrid.tsx

This PR fixes:
- Footer overflow on data grid table

[OBSDEF-18239] Fix footer issue on datagrid table

---

package.json
src/layout/vertical-nav/VerticalNav.stories.tsx
src/layout/vertical-nav/VerticalNavGroup.tsx

**Summary :** 
- Added new prop "isExpanded" in `VerticalNavGroup` component. To check if Nav Group is already active and expanded.
- Added story for same
**Test Link:** 
storybook :   http://10.86.76.248:6006/ 
Storybook:
vSphere plugin :

[OBSDEF-OBSDEF-18714] isExpanded prop for already active vertical navigation group

---

package.json
src/accordian/Accordion.tsx

[OBSDEF-19538](https://jira.cec.lab.emc.com/browse/OBSDEF-19538)
List of changes:
- added condition based caret direction for open and closed.
Note: Given direction up to icon when accordion is open because @clr/ui rotates the icon to 180deg so it will eventually points downwards.
Standalone After change
Vsphere After Change:
Storybook After change:
Test Url: http://10.249.253.4:3007
token: eyJhbGciOiJSUzI1NiIsImtpZCI6Im9RNE1BLVlFNU5GYi1qZDdrTld1OG9yVmpmZXhHcW9USkJEWWZNM1MxV1UifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJzdmMtb2JqZWN0c2NhbGUtZG9tYWluLWMyMCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJvYmplY3RzY2FsZS1vcGVyYXRvci10b2tlbi1qYjQycSIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50Lm5hbWUiOiJ …

[OBSDEF-19538] accordion caret open icon fix

---

package.json
src/datagrid/DataGrid.tsx

This PR is for the ticket [OBSDEF-19780] -> upgrade -> pt#3 (in description)
Issue: 
Datagrid footer item text is not getting updated even after providing correct props.
Resolution: 
Footer item text is now taken from props itself. Earlier it was taken from state. Now removed state for item text.
Tested by patching it to the local workspace. Working fine
Storybook link: http://10.249.253.4:6006

[OBSDEF-19780] Datagrid footer

---

src/datagrid/DataGridFilter.tsx

In this PR we have fixed the filter and it is now appearing on the top of the container and Footer. Also we have implemented that when ever we scroll on the page the filter gets close.
Test Link:
http://10.249.253.4:3003/

[OBSDEF-25568] Datagrid Filter overlay fix

---

CODEOWNERS
package.json
src/datagrid/DataGridFilter.tsx

- Bumped version of clarity-react
- Added check on scroll event for Datagrid filter. It will now only close if the scroll event is not caused by input
There is a problem currently where adding a long input which does not fit the datagrid filter box makes a scroll event.
Because of this, inputs that are large cannot be added to DatagridFilter.
However, scroll listener was added to close the DatagridFilter on scrolling up or down as without it, the datagrid filter was detaching from the datagrid itself.
Hence modified the code to not close filter if input exceeds datagrid size
https://jira.cec.lab.emc.com/browse/OBSDEF-38858
Jumpbox Link: http://10.227.242.14:3000
Credentials: root/ChangeMe@123

[OBSDEF-38858] Adding values for datagrid filter

---

package.json

This is to merely bump the package.json version
Please refer: https://github.com/EMCECS/clarity-react/pull/269#discussion_r1454556314

Bumping package.json module version

---

package.json
src/forms/datepicker/DatePicker.tsx

Before
After
Did some changes to disable the future dates in DatePicker for https://jira.cec.lab.emc.com/browse/OBSDEF-40971.

[OBSDEF-40971] disabled future dates in datepicker

---

package.json
src/datagrid/DataGrid.stories.tsx
src/datagrid/DataGrid.tsx
src/datagrid/DataGridStoriesData.tsx
src/utils.ts

[OBSDEF-45527](https://jira.cec.lab.emc.com/browse/OBSDEF-45527)
- Made Pagination -> PageSizes prop as optional
- Remove all changes related to default prop for PageSizes
- Added validation for custom page size input for accepting only number values
- Replace deprecated `evt.keycode` with `evt.key`
- Create constant for "Custom" option
- Create enum for common Keyboard keys
- Updated missing documentation
NA
###
http://10.227.234.153:6006/?path=/story/datagrid--grid-with-pagination-and-pagesizes-dropdown
_List all the scenarios verified for the changes or link to the manual test documentation for new features_
_Add team member's name who will test your PR_
@netraja-chavan

[OBSDEF-46956] DataGrid Pagination Improvments: Revert default prop changes for PageSizes

---

package.json
src/datagrid/DataGrid.stories.tsx
src/datagrid/DataGrid.tsx
src/datagrid/DataGridStoriesData.tsx

[OBSDEF-44980](https://jira.cec.lab.emc.com/browse/OBSDEF-44980)
- Added code to show pagination footer with page sizes dropdown only if the total number of records are greater than 10
- Created story for same
NA
Storybook:
Objectscale Portal UI:
Storybook : 
http://10.227.234.153:6006/?path=/story/datagrid--grid-with-pagination-and-pagesizes-dropdown
ObjectScale Portal UI:
http://10.227.234.153:3000/#
_List all the scenarios verified for the changes or link to the manual test documentation for new features_
_Add team member's name who will test your PR_
@netraja-chavan

[OBSDEF-44980] Show pagination footer with page sizes dropdown only if number of records are greater than 10
